# Generated by Django 5.0.3 on 2024-10-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GestionLocal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="local",
            name="area_m2",
        ),
        migrations.RemoveField(
            model_name="local",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="local",
            name="imagen_url",
        ),
        migrations.RemoveField(
            model_name="local",
            name="latitud",
        ),
        migrations.RemoveField(
            model_name="local",
            name="longitud",
        ),
        migrations.RemoveField(
            model_name="local",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="localidad",
            name="latitud_centro",
        ),
        migrations.RemoveField(
            model_name="localidad",
            name="longitud_centro",
        ),
        migrations.RemoveField(
            model_name="preferenciasusuario",
            name="usuario",
        ),
        migrations.AddField(
            model_name="local",
            name="area",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="local",
            name="titulo",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="local",
            name="localidad",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="local",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="localidad",
            name="radio_geografico",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="preferenciasusuario",
            name="area_max",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="preferenciasusuario",
            name="area_min",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="preferenciasusuario",
            name="precio_max",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="preferenciasusuario",
            name="precio_min",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
